### ISSUE TITLE
Negative reading for pressure

### ISSUE THREAD

**Issue by giovanni-foorban** [rv701/SPL06-007#3]
Hello, I used your example and I am getting a good reading for temperature while the pressure is negative. Any clue on what the problem could be?

I leave all the logging from your example below
ID: 16
PRS_CFG: 11
TMP_CFG: 10000011
MEAS_CFG: 11110111
CFG_REG: 0
INT_STS: 0
FIFO_STS: 0
c0: 197
c1: -251
c00: 80432
c10: 996536
c01: -2992
c11: 1478
c20: -10470
c21: 272
c30: -1624
traw: 2454514
traw_sc: 0.312
Temperature: 20.16 C
Temperature: 68.29 F
praw: -3526768
praw_sc: -0.448
pcomp: -369549.03
Measured Air Pressure: -3695.49 mb
Local Airport Sea Level Pressure: 1011.30 mb
altitude: nan m
altitude: nan ft

**Comment by gioclava** [comment]
I fixed your code, you have a mistake for the calculation of 2 coefficients:

int32_t get_c00()
{
  int32_t tmp; 
  uint8_t tmp_MSB,tmp_LSB,tmp_XLSB;
  
  tmp_MSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X13); 
  tmp_LSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X14); 
  tmp_XLSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X15);
  tmp = (tmp_MSB & 0x80 ? 0xFFF00000 : 0) | ((uint32_t)tmp_MSB << 12) | ((uint32_t)tmp_LSB << 4) | (((uint32_t)tmp_XLSB & 0xF0) >> 4);
  return tmp;
}

int32_t get_c10()
{
  int32_t tmp; 
  uint8_t tmp_MSB,tmp_LSB,tmp_XLSB;
  
  tmp_MSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X15); // 4 bits
  tmp_LSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X16); // 8 bits
  tmp_XLSB = i2c_eeprom_read_uint8_t(SPL_CHIP_ADDRESS, 0X17); // 8 bits
  tmp = (tmp_MSB & 0x8 ? 0xFFF00000 : 0) | (((uint32_t)tmp_MSB & 0x0F) << 16) | ((uint32_t)tmp_LSB << 8) | (uint32_t)tmp_XLSB;
  return tmp;
}

**Comment by plusmartin** [comment]
what exactly did you correct?

original:
 
  tmp_XLSB = tmp_XLSB >> 4;

 
  tmp = (tmp_MSB << 8) | tmp_LSB;
  tmp = (tmp << 4) | tmp_XLSB;

  tmp = (uint32_t)tmp_MSB << 12 | (uint32_t)tmp_LSB << 4 | (uint32_t)tmp_XLSB >> 4;

  if(tmp & (1 << 19))
    tmp = tmp | 0XFFF00000; // Set left bits to one for 2's complement conversion of negitive number
   
  return tmp;



_________________




correction:

tmp = (tmp_MSB & 0x80 ? 0xFFF00000 : 0) | ((uint32_t)tmp_MSB << 12) | ((uint32_t)tmp_LSB << 4) | (((uint32_t)tmp_XLSB & 0xF0) >> 4);
return tmp;

**Comment by gioclava** [comment]
I think many some shifting were wrong. I also ended up reimplementing many things for this project: https://github.com/gioclava/barometer

I have also changed the the precision configuration. The code is pretty messy in that repo and you will have to make changes as i am reading 2 baros instead of one, but at least you have a correct starting point.

**Comment by rv701** [comment]
I was using a ESP32 for my testing and I did not notice the issue. I tested on an ESP32, SAMD21, and an Arduino Nano. I was able to repeat the issue with the Nano. I updated the code with your changes. Out of curiosity what micro controller are you using? Thanks for the update.

**Comment by giovanni-foorban** [comment]
An atmega328p, so yes like an Arduino nano. I am happy it helped!

Il mer 5 mag 2021, 05:50 rv701 ***@***.***> ha scritto:

**Comment by 1971Merlin** [comment]
I still get errors with the updated _c00 and _c10 routines:

ID: 16
PRS_CFG: 11
TMP_CFG: 10000011
MEAS_CFG: 11110111
CFG_REG: 0
INT_STS: 0
FIFO_STS: 0
c0: 199
c1: -253
c00: 79216
c10: 995985
c01: -3139
c11: 1559
c20: -10387
c21: 99
c30: -1476
traw: 2307042
traw_sc: 0.293
Temperature: 25.28 C
Temperature: 77.51 F
praw: -3721812
praw_sc: -0.473
pcomp: -395437.46
Measured Air Pressure: -3954.37 mb
Local Airport Sea Level Pressure: 1016.00 mb
altitude: nan m
altitude: nan ft


Edit --- the fixes in this pull: https://github.com/rv701/SPL06-007/pull/5 resolve my issues.

**Comment by destino152** [comment]
I get the same issue with an Arduino UNO

I get a barometric pressure reading of  -2946 mbar  This is clearly incorrect the highest ever reading was 1083.8mb and the lowest ever was 870 mbar. For a while i thought it was the units that were wrong but I couldn't find any unit that made sense.

Following a comment that was made by the author  I changed to an ESP32 and everything appears to be working. I now get a Barometric Pressure reading of 998.99 mbar which seems a little low. Temperatures and altitude are about right. However they were always as expected.

So it seems that the library has some issues with calculating Barometric Pressure on non ESP32 boards.

I don't have the skills to delve deeper. I'll leave it to the smart and clever folks here.

Cheers and thanks.

Peter
